import { APP_NAME } from "@/lib/constants/app";
import { ILLUSTRATIONS } from "@/lib/constants/illustrations";
import { profileSettingsUrl } from "@/lib/utils/app-url";

export const EMAIL_TEMPLATE_VARIABLES: Record<string, string[]> = {
  "cancellation-request-admin": [
    "commune_name",
    "commune_postcode",
    "user_name",
    "user_email",
    "request_date",
    "comment",
    "logo_url",
    "app_name",
  ],
  "cancellation-confirmation-staff": [
    "commune_name",
    "user_name",
    "subscription_end_date",
    "comment",
    "logo_url",
    "app_name",
  ],
  "trial-invitation": [
    "commune_name",
    "access_code",
    "signup_url",
    "logo_url",
    "app_name",
  ],
  "report-notification-staff": [
    "commune_name",
    "content_type",
    "content_title",
    "reporter_name",
    "reason",
    "report_date",
    "moderation_url",
    "logo_url",
    "app_name",
  ],
  "report-notification-admin": [
    "commune_name",
    "content_type",
    "content_title",
    "reporter_name",
    "reason",
    "report_date",
    "moderation_url",
    "logo_url",
    "app_name",
  ],
  "neighbor-invite": [
    "sender_name",
    "commune_name",
    "invite_link",
    "logo_url",
    "app_name",
  ],
  "email-verification": [
    "user_name",
    "verification_link",
    "logo_url",
    "app_name",
  ],
  "email-change-verification": [
    "user_name",
    "new_email",
    "verification_link",
    "logo_url",
    "app_name",
  ],
  "content-suspended": [
    "user_name",
    "commune_name",
    "content_type",
    "content_title",
    "suspension_reason",
    "content_url",
    "support_email",
    "logo_url",
    "app_name",
  ],
  "user-suspended": [
    "user_name",
    "commune_name",
    "suspension_reason",
    "appeal_url",
    "support_email",
    "logo_url",
    "app_name",
  ],
  "user-banned": [
    "user_name",
    "ban_reason",
    "support_email",
    "logo_url",
    "app_name",
  ],
  "user-restored": [
    "user_name",
    "restoration_summary",
    "app_url",
    "support_email",
    "logo_url",
    "app_name",
  ],
  "content-restored": [
    "user_name",
    "commune_name",
    "content_type",
    "content_title",
    "content_url",
    "support_email",
    "logo_url",
    "app_name",
  ],
  "invite-reminder": [
    "sender_name",
    "commune_name",
    "invite_link",
    "settings_url",
    "logo_url",
    "app_name",
  ],
  "engagement-first-week": [
    "user_name",
    "commune_name",
    "app_url",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
  "announcement-expired-nudge": [
    "user_name",
    "announcement_title",
    "announcement_url",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
  "announcement-stale-60d": [
    "user_name",
    "announcement_title",
    "announcement_url",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
  "initiative-stale-60d": [
    "user_name",
    "initiative_title",
    "initiative_url",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
  "event-past-nudge": [
    "user_name",
    "event_title",
    "event_url",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
  "notification-activation-reminder": [
    "user_name",
    "commune_name",
    "settings_url",
    "unsubscribe_link",
    "logo_url",
    "app_name",
  ],
};

export function getEmailTemplateVariables(slug: string): string[] {
  return EMAIL_TEMPLATE_VARIABLES[slug] ?? ["logo_url", "app_name"];
}

export function getEmailTemplateMockValue(variable: string): string {
  const mocks: Record<string, string> = {
    commune_name: "Les Authieux",
    commune_postcode: "27220",
    user_name: "Jean Dupont",
    user_email: "jean.dupont@example.fr",
    new_email: "nouvelle.adresse@example.fr",
    request_date: "12 juin 2026",
    subscription_end_date: "31 déc. 2026",
    comment: "Première ligne du commentaire.\nDeuxième ligne pour tester les retours à la ligne.",
    access_code: "VL-KAMET",
    signup_url: "http://localhost:3000/inscription?commune=27027&code=VL-KAMET",
    content_type: "Annonce",
    content_title: "Recherche aide pour déménagement",
    reporter_name: "Marie Martin",
    reason: "Contenu inapproprié ou trompeur.\nPlusieurs passages posent problème.\nMerci de vérifier.",
    report_date: "17 juin 2026",
    moderation_url: "https://app.tous-voisins.fr/mairie/signalements",
    sender_name: "Marie Dupont",
    invite_link:
      "http://localhost:3000/inscription?invite=abc123def456&commune=27027&email=voisin@exemple.fr",
    verification_link:
      "http://localhost:3000/auth/callback?type=magiclink&token_hash=example-token",
    suspension_reason:
      "Contenu ne respectant pas les règles de la communauté.\nDétails supplémentaires ici.",
    ban_reason:
      "Violation répétée des conditions d'utilisation.\nMalgré plusieurs avertissements.",
    content_url: "http://localhost:3000/annonces/abc123",
    appeal_url: "http://localhost:3000/suspendu",
    restoration_summary: "Votre accès à Les Authieux a été rétabli.",
    app_url: "http://localhost:3000/accueil",
    settings_url: profileSettingsUrl(),
    unsubscribe_link: "http://localhost:3000/unsubscribe?token=example-token",
    announcement_title: "Recherche aide pour déménagement",
    announcement_url: "http://localhost:3000/annonces/abc123",
    initiative_title: "Jardin partagé du quartier",
    initiative_url: "http://localhost:3000/initiatives/def456",
    event_title: "Fête des voisins 2026",
    event_url: "http://localhost:3000/evenements/ghi789",
    support_email: "support@tous-voisins.fr",
    logo_url: ILLUSTRATIONS.auth.logoHorizontal,
    app_name: APP_NAME,
  };
  return mocks[variable] ?? `[${variable}]`;
}
