#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/public/logo-square.png"
APPLE="$ROOT/public/apple-touch-icon.png"
APP_APPLE="$ROOT/app/apple-icon.png"
APP_ICON="$ROOT/app/icon.png"
FAVICON16="$ROOT/public/favicon-16x16.png"
ICON192="$ROOT/public/icons/icon-192.png"
ICON512="$ROOT/public/icons/icon-512.png"
CONSTANTS="$ROOT/lib/constants/pwa-icons.ts"
MANIFEST="$ROOT/public/manifest.webmanifest"
STALE_FAVICON="$ROOT/app/favicon.ico"

if [[ ! -f "$SRC" ]]; then
  echo "Missing source icon: public/logo-square.png" >&2
  exit 1
fi

if ! command -v sips >/dev/null 2>&1; then
  if [[ -f "$APPLE" && -f "$ICON192" && -f "$ICON512" && -f "$APP_APPLE" && -f "$APP_ICON" ]]; then
    echo "sips not available; using committed PWA icons."
    exit 0
  fi
  echo "sips is required to generate PWA icons (macOS)." >&2
  exit 1
fi

WIDTH=$(sips -g pixelWidth "$SRC" | awk '/pixelWidth/ { print $2 }')
HEIGHT=$(sips -g pixelHeight "$SRC" | awk '/pixelHeight/ { print $2 }')
VERSION=$(md5 -q "$SRC" | cut -c1-8)

mkdir -p "$ROOT/public/icons"

resize_icon() {
  local px="$1"
  local out="$2"
  sips -z "$px" "$px" "$SRC" --out "$out" >/dev/null
}

for spec in "32:$APP_ICON" "16:$FAVICON16" "180:$APPLE" "180:$APP_APPLE" "192:$ICON192" "512:$ICON512"; do
  px="${spec%%:*}"
  out="${spec#*:}"
  resize_icon "$px" "$out"
done

rm -f "$STALE_FAVICON"

cat > "$CONSTANTS" <<EOF
/** Auto-generated by scripts/generate-pwa-icons.sh — do not edit manually. */
export const PWA_ICON_VERSION = "${VERSION}";
EOF

ROOT="$ROOT" node <<'NODE'
const fs = require("fs");
const path = require("path");

const root = process.env.ROOT;
const manifestPath = path.join(root, "public/manifest.webmanifest");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

// No query strings — iOS installers reject them.
// "maskable" only → Android displays the icon full-bleed (no background_color plate).
// iOS ignores maskable icons from the manifest but uses <link rel="apple-touch-icon"> from HTML instead.
manifest.background_color = "#9A52FF";
manifest.theme_color = "#9A52FF";
manifest.icons = [
  {
    src: "/icons/icon-192.png",
    sizes: "192x192",
    type: "image/png",
    purpose: "maskable",
  },
  {
    src: "/icons/icon-512.png",
    sizes: "512x512",
    type: "image/png",
    purpose: "maskable",
  },
];

fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
NODE

echo "PWA icons generated from logo-square.png (${WIDTH}x${HEIGHT}, v${VERSION})"
