#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/public/logo-square.png"
TMP="$ROOT/public/.pwa-icon-source.png"
APPLE="$ROOT/public/apple-touch-icon.png"
APP_APPLE="$ROOT/app/apple-icon.png"
ICON192="$ROOT/public/icons/icon-192.png"
ICON512="$ROOT/public/icons/icon-512.png"
CONSTANTS="$ROOT/lib/constants/pwa-icons.ts"
MANIFEST="$ROOT/public/manifest.webmanifest"

if [[ ! -f "$SRC" ]]; then
  echo "Missing source icon: public/logo-square.png" >&2
  exit 1
fi

if ! command -v sips >/dev/null 2>&1; then
  if [[ -f "$APPLE" && -f "$ICON192" && -f "$ICON512" && -f "$APP_APPLE" ]]; then
    echo "sips not available; using committed PWA icons."
    exit 0
  fi
  echo "sips is required to generate PWA icons (macOS)." >&2
  exit 1
fi

flatten_png() {
  local input="$1"
  local output="$2"
  local tmp_jpg="${output%.png}.jpg"

  # iOS is more reliable with opaque RGB icons than RGBA.
  sips -s format jpeg "$input" --out "$tmp_jpg" >/dev/null
  sips -s format png "$tmp_jpg" --out "$output" >/dev/null
  rm -f "$tmp_jpg"
}

WIDTH=$(sips -g pixelWidth "$SRC" | awk '/pixelWidth/ { print $2 }')
HEIGHT=$(sips -g pixelHeight "$SRC" | awk '/pixelHeight/ { print $2 }')
SIZE=$(( WIDTH > HEIGHT ? WIDTH : HEIGHT ))
VERSION=$(md5 -q "$SRC" | cut -c1-8)

mkdir -p "$ROOT/public/icons"
cp "$SRC" "$TMP"
sips -p "$SIZE" "$SIZE" "$TMP" --out "$TMP" >/dev/null

for spec in "180:$APPLE" "180:$APP_APPLE" "192:$ICON192" "512:$ICON512"; do
  px="${spec%%:*}"
  out="${spec#*:}"
  resized="${out%.png}.resized.png"
  sips -z "$px" "$px" "$TMP" --out "$resized" >/dev/null
  flatten_png "$resized" "$out"
  rm -f "$resized"
done

rm -f "$TMP"

cat > "$CONSTANTS" <<EOF
/** Auto-generated by scripts/generate-pwa-icons.sh — do not edit manually. */
export const PWA_ICON_VERSION = "${VERSION}";
EOF

ROOT="$ROOT" VERSION="$VERSION" node <<'NODE'
const fs = require("fs");
const path = require("path");

const root = process.env.ROOT;
const version = process.env.VERSION;
const manifestPath = path.join(root, "public/manifest.webmanifest");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));

manifest.icons = [
  {
    src: `/icons/icon-192.png?v=${version}`,
    sizes: "192x192",
    type: "image/png",
    purpose: "any",
  },
  {
    src: `/icons/icon-512.png?v=${version}`,
    sizes: "512x512",
    type: "image/png",
    purpose: "any",
  },
];

fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
NODE

echo "PWA icons generated from logo-square.png (${WIDTH}x${HEIGHT} -> ${SIZE}x${SIZE}, v${VERSION})"
